# Generated by Django 5.0.7 on 2024-08-01 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("transmission", models.CharField(max_length=50)),
                ("gears", models.CharField(max_length=50)),
                ("engine", models.CharField(max_length=50)),
                ("seat_height", models.CharField(max_length=50)),
                ("weight", models.CharField(max_length=50)),
                ("power", models.CharField(max_length=50)),
                ("tank_size", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                (
                    "bike",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="availbikes.bike",
                    ),
                ),
            ],
        ),
    ]
